"""Editable source definitions for dissertation control/monitoring figures.

The companion ``build_figures.py`` script renders these definitions to PDF
using only the Python standard library.
"""

PALETTE = {
    "ui": {"label": "Operator interface", "fill": "#e9f1ff", "stroke": "#2f6fdd", "text": "#152b4f"},
    "supervisor": {"label": "Supervisor computer", "fill": "#f0eaff", "stroke": "#7450b8", "text": "#2f1f4c"},
    "firmware": {"label": "Firmware controller", "fill": "#e8f6ee", "stroke": "#2d8a4a", "text": "#163b25"},
    "sensor": {"label": "Instrumentation", "fill": "#fff5de", "stroke": "#b87900", "text": "#4a3200"},
    "actuator": {"label": "Actuation", "fill": "#ffece7", "stroke": "#d15b3b", "text": "#4c1d12"},
    "safety": {"label": "Safety limit", "fill": "#ffe8ee", "stroke": "#c4314b", "text": "#541321"},
    "data": {"label": "Data products", "fill": "#edf1f4", "stroke": "#66717d", "text": "#26323d"},
    "logic": {"label": "Control logic", "fill": "#e5f6f7", "stroke": "#238485", "text": "#103f40"},
    "note": {"label": "Reference note", "fill": "#f8f8f3", "stroke": "#a0a08a", "text": "#333333"},
    "arch_operator": {"label": "Operator/computer side", "fill": "#eef4ff", "stroke": "#4f6f9f", "text": "#1f344f"},
    "arch_firmware": {"label": "Arduino firmware", "fill": "#edf8f1", "stroke": "#2f7d4d", "text": "#173c27"},
    "arch_hardware": {"label": "Physical hardware", "fill": "#fff6e3", "stroke": "#946b1f", "text": "#4a3510"},
    "arch_data": {"label": "Logged data", "fill": "#f1f4f7", "stroke": "#5f6b76", "text": "#26323d"},
    "overview_supervisor": {"label": "Supervisor", "fill": "#fbf8ff", "stroke": "#7450b8", "text": "#2f1f4c"},
    "overview_power": {"label": "Power source", "fill": "#fbfaf5", "stroke": "#8a8170", "text": "#333333"},
    "overview_controller": {"label": "Controller", "fill": "#f3fbf7", "stroke": "#2d8a4a", "text": "#163b25"},
    "overview_instrumentation": {"label": "Instrumentation", "fill": "#fffaf0", "stroke": "#b87900", "text": "#4a3200"},
    "overview_interface": {"label": "Signal interface", "fill": "#f2fbfb", "stroke": "#238485", "text": "#103f40"},
    "overview_actuation": {"label": "Actuation/load", "fill": "#fff7f4", "stroke": "#d15b3b", "text": "#4c1d12"},
    "tc_header": {"label": "Backplate header", "fill": "#f4f7fb", "stroke": "#657485", "text": "#26323d"},
    "tc_active_t": {"label": "Type-T MAX31856", "fill": "#f5f0ff", "stroke": "#7b5ac6", "text": "#2f1f4c"},
    "tc_active_k": {"label": "Type-K MAX31856", "fill": "#fff2e8", "stroke": "#c66a24", "text": "#4a240b"},
    "tc_spare": {"label": "Spare socket", "fill": "#f3f5f7", "stroke": "#9aa4af", "text": "#343d46"},
    "wire_data": {"label": "Signal", "fill": "#fff0a8", "stroke": "#c99a00", "text": "#453500"},
    "wire_24v": {"label": "24 VDC", "fill": "#ffe1e1", "stroke": "#d12d2d", "text": "#5a1111"},
    "wire_5v": {"label": "5 VDC", "fill": "#eeeeee", "stroke": "#1f252b", "text": "#111111"},
    "wire_vin": {"label": "V_{in}", "fill": "#eeeeee", "stroke": "#1f252b", "text": "#111111"},
    "wire_gnd": {"label": "GND", "fill": "#e7f6e7", "stroke": "#238444", "text": "#143f24"},
    "wire_sdi_sdo": {"label": "SDI/SDO", "fill": "#fff0a8", "stroke": "#c99a00", "text": "#453500"},
    "wire_sck": {"label": "SCK", "fill": "#ffe5c2", "stroke": "#d87600", "text": "#552d00"},
    "wire_cs": {"label": "CS", "fill": "#f3e9ff", "stroke": "#7b4bb5", "text": "#2f1f4c"},
    "wire_black": {"label": "120 VAC / 5 VDC", "fill": "#eeeeee", "stroke": "#1f252b", "text": "#111111"},
    "wire_com": {"label": "COM", "fill": "#e6efff", "stroke": "#1e63d6", "text": "#123b7a"},
    "wire_earth": {"label": "Earth", "fill": "#e7f6e7", "stroke": "#238444", "text": "#143f24"},
    "wire_240": {"label": "240 VAC 3ph", "fill": "#f4f4f4", "stroke": "#59636e", "text": "#222222"},
}


FIGURES = [
    {
        "slug": "01_control_telemetry_architecture",
        "title": "Control, Telemetry, and Logging Architecture",
        "show_title": False,
        "caption": (
            "Combined system and firmware-loop view. UI commands pass from the lab computer to "
            "the Arduino over USB serial. Manual output commands are applied by the firmware, "
            "while stored auto settings are used in the scheduled 1 Hz measurement, control, "
            "and telemetry pass. Box shading separates the operator/computer side, Arduino "
            "firmware, physical hardware, and logged data."
        ),
        "size": [1500, 620],
        "elements": [
            {"type": "box", "group": "arch_operator", "x": 40, "y": 185, "w": 190, "h": 135,
             "label": "Operator panel",
             "body": "Enters setpoints and shows live status", "label_size": 21, "body_size": 17},
            {"type": "box", "group": "arch_operator", "x": 268, "y": 185, "w": 220, "h": 135,
             "label": "Lab computer",
             "body": "Runs the web server, serial bridge, and CSV logger", "label_size": 21, "body_size": 17},
            {"type": "box", "group": "arch_firmware", "x": 526, "y": 185, "w": 165, "h": 135,
             "label": "Command input",
             "body": "Arduino receives serial commands and updates settings", "label_size": 18, "body_size": 14},
            {"type": "box", "group": "arch_firmware", "x": 729, "y": 185, "w": 165, "h": 135,
             "label": "1 Hz firmware step",
             "body": "Starts each measurement-control pass", "label_size": 18, "body_size": 14},
            {"type": "box", "group": "arch_firmware", "x": 932, "y": 185, "w": 165, "h": 135,
             "label": "Sensor readout",
             "body": "Temperatures, pressures, flow meter, and VFD feedback", "label_size": 18, "body_size": 15},
            {"type": "box", "group": "arch_firmware", "x": 1135, "y": 185, "w": 155, "h": 135,
             "label": "Control logic",
             "body": "LN valve auto mode and pump pressure interlock", "label_size": 18, "body_size": 15},
            {"type": "box", "group": "arch_firmware", "x": 1328, "y": 185, "w": 145, "h": 135,
             "label": "Arduino outputs",
             "body": "Sets actuators; sends telemetry", "label_size": 17, "body_size": 14},
            {"type": "box", "group": "arch_hardware", "x": 932, "y": 425, "w": 541, "h": 120,
             "label": "Physical HFE loop",
             "body": "Experimental hardware connected to the Arduino: thermocouples, pressure sensors, flow meter, VFD/pump, LN valve, heaters", "body_size": 17},
            {"type": "box", "group": "arch_data", "x": 268, "y": 425, "w": 220, "h": 110,
             "label": "Logged data",
             "body": "Timestamped CSV records for analysis", "body_size": 17},
            {"type": "arrow", "points": [[230, 235], [268, 235]], "label": "SSH / HTTP", "label_dy": -65, "label_w": 110, "label_box_w": 110},
            {"type": "arrow", "points": [[268, 285], [230, 285]], "label": "WebSocket", "label_dy": 65, "label_w": 100, "label_box_w": 100},
            {"type": "arrow", "points": [[488, 235], [526, 235]], "label": "USB serial command", "label_dy": -65, "label_w": 170, "label_box_w": 190},
            {"type": "arrow", "points": [[691, 252], [729, 252]]},
            {"type": "arrow", "points": [[894, 252], [932, 252]]},
            {"type": "arrow", "points": [[1097, 252], [1135, 252]]},
            {"type": "arrow", "points": [[1290, 252], [1328, 252]]},
            {"type": "arrow", "points": [[1040, 425], [1040, 320]], "label": "sensor/VFD feedback", "label_dx": -112, "label_dy": -4, "label_w": 165, "label_box_w": 170},
            {"type": "arrow", "points": [[1398, 320], [1398, 425]], "label": "actuator I/O", "label_dx": -80, "label_dy": -4, "label_w": 105},
            {"type": "arrow", "points": [[1450, 185], [1450, 70], [378, 70], [378, 185]], "label": "USB serial telemetry", "dashed": True, "label_dx": 0, "label_dy": -22, "label_w": 175, "label_box_w": 180},
            {"type": "arrow", "points": [[378, 320], [378, 425]], "label": "CSV log", "label_dx": 45, "label_dy": -6, "label_w": 90},
            {"type": "arrow", "points": [[1351, 185], [1351, 125], [812, 125], [812, 185]], "label": "next 1 Hz pass", "dashed": True, "label_dx": 0, "label_dy": 24, "label_w": 130, "label_box_w": 135},
        ],
    },
    {
        "slug": "02_ln_valve_auto_logic",
        "title": "LN Valve Auto-Mode Logic",
        "caption": (
            "Automatic liquid-nitrogen valve control. Each scan reads the TMI and THI "
            "temperatures, closes on cold-limit conditions, and reopens only after both "
            "recovery criteria are satisfied."
        ),
        "size": [1370, 860],
        "show_title": False,
        "elements": [
            {"type": "box", "group": "logic", "x": 45, "y": 245, "w": 190, "h": 105,
             "label": "AUTO mode enabled",
             "body": "", "label_size": 27, "body_size": 17},
            {"type": "io", "group": "sensor", "x": 285, "y": 232, "w": 225, "h": 130,
             "label": "Read HX & HFE temperatures",
             "body": "", "label_size": 27, "body_size": 17, "text_w": 175},
            {"type": "decision", "group": "safety", "x": 560, "y": 210, "w": 210, "h": 175,
             "label": "Inputs\nvalid?",
             "body": "", "label_size": 27, "body_size": 16, "text_w": 130},
            {"type": "decision", "group": "safety", "x": 820, "y": 210, "w": 220, "h": 175,
             "label": "HX too\ncold?",
             "body": "", "label_size": 27, "body_size": 16, "text_w": 145},
            {"type": "decision", "group": "safety", "x": 1080, "y": 210, "w": 220, "h": 175,
             "label": "HFE at\ngoal?",
             "body": "", "label_size": 27, "body_size": 16, "text_w": 145},
            {"type": "decision", "group": "logic", "x": 1080, "y": 465, "w": 220, "h": 175,
             "label": "Valve\nclosed?",
             "body": "", "label_size": 27, "body_size": 15, "text_w": 145},
            {"type": "decision", "group": "logic", "x": 820, "y": 465, "w": 220, "h": 175,
             "label": "HX\nrecovered?",
             "body": "", "label_size": 27, "body_size": 16, "text_w": 150},
            {"type": "decision", "group": "logic", "x": 560, "y": 465, "w": 210, "h": 175,
             "label": "HFE\nrecovered?",
             "body": "", "label_size": 27, "body_size": 16, "text_w": 150},
            {"type": "box", "group": "actuator", "x": 1055, "y": 20, "w": 270, "h": 110,
             "label": "Close valve",
             "body": "", "label_size": 27, "body_size": 18, "center_text": True},
            {"type": "box", "group": "actuator", "x": 1055, "y": 720, "w": 270, "h": 110,
             "label": "Open valve",
             "body": "", "label_size": 27, "body_size": 18, "center_text": True},
            {"type": "arrow", "points": [[235, 297.5], [300.75, 297.5]]},
            {"type": "arrow", "points": [[494.25, 297.5], [560, 297.5]]},
            {"type": "arrow", "points": [[770, 297.5], [820, 297.5]], "label": "yes", "label_dx": 0, "label_dy": -30, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[665, 210], [665, 75], [1055, 75]], "label": "no", "label_dx": -95, "label_dy": 105, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[1040, 297.5], [1080, 297.5]], "label": "no", "label_dx": 0, "label_dy": -30, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[930, 210], [930, 75], [1055, 75]], "label": "yes", "label_dx": 40, "label_dy": 105, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[1190, 210], [1190, 130]], "label": "yes", "label_dx": 40, "label_dy": 15, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[1190, 385], [1190, 465]], "label": "no", "label_dx": 40, "label_dy": 0, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[1080, 552.5], [1040, 552.5]], "label": "yes", "label_dx": 0, "label_dy": -30, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[1190, 640], [1190, 720]], "label": "no", "label_dx": 40, "label_dy": 0, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "arrow", "points": [[820, 552.5], [770, 552.5]], "label": "yes", "label_dx": 0, "label_dy": -30, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "wire", "points": [[930, 640], [930, 845]], "label": "no", "label_dx": 40, "label_dy": -62.5, "label_w": 45, "label_size": 19, "label_box_w": 58, "dashed": True, "width": 2.6},
            {"type": "arrow", "points": [[665, 640], [665, 775], [1055, 775]], "label": "yes", "label_dx": -88, "label_dy": -95, "label_w": 45, "label_size": 19, "label_box_w": 58},
            {"type": "wire", "points": [[560, 552.5], [397.5, 552.5]], "label": "no", "label_dx": 48, "label_dy": -20, "label_w": 45, "label_size": 19, "label_box_w": 58, "dashed": True, "width": 2.6},
            {"type": "arrow", "points": [[1190, 20], [1190, 5], [397.5, 5], [397.5, 232]],
             "label": "next scan", "dashed": True, "label_dx": 0, "label_dy": 30,
             "label_w": 105, "label_size": 19, "label_box_w": 125},
            {"type": "arrow", "points": [[1190, 830], [1190, 845], [397.5, 845], [397.5, 362]],
             "label": "next scan", "dashed": True, "label_dx": 128, "label_dy": -29,
             "label_w": 105, "label_size": 19, "label_box_w": 125},
        ],
    },
    {
        "slug": "03_key_measurements",
        "title": "Key Measurements and Interlocks",
        "caption": (
            "Experimental signals used for control, monitoring, and later analysis. The table "
            "keeps hardware context without listing implementation-level field names."
        ),
        "size": [1500, 980],
        "elements": [
            {
                "type": "table",
                "x": 60,
                "y": 145,
                "w": 1380,
                "row_h": 78,
                "font_size": 18,
                "columns": [
                    ["Quantity", 260],
                    ["Sensor or interface", 420],
                    ["Use in the experiment", 700],
                ],
                "rows": [
                    ["TMI", "Thermocouple at the HFE control point", "Primary liquid-temperature feedback for the HFE cooling goal and LN valve auto mode."],
                    ["THI", "Heat-exchanger inlet thermocouple", "Cold-side guard temperature used to prevent excessive heat-exchanger cooling."],
                    ["TTI / TTO", "Tank inlet and outlet thermocouples", "Temperature difference across the tank loop and general cooldown monitoring."],
                    ["PMI / PMO", "Pressure transducers before and after the pump", "Pump pressure rise; delta-P above 8.0 bar trips the firmware emergency stop."],
                    ["PTA", "Tank pressure transducer", "Tank absolute pressure monitoring during filling, cooldown, and circulation."],
                    ["Flow meter", "MFC400 serial flow meter", "Independent flow, density, and fluid-temperature reference during circulation."],
                    ["VFD feedback", "Pump drive serial monitor", "Drive frequency, current, voltage, power, and estimated speed for pump-performance checks."],
                    ["Scale", "Independent USB scale reader", "Liquid-nitrogen mass trend attached to telemetry for cooldown accounting."],
                    ["Actuators", "Pump PWM, LN valve relay, heater relays", "Commands applied by the firmware after manual requests and safety checks."],
                ],
            }
        ],
    },
    {
        "slug": "04_electrical_wiring_overview",
        "title": "Electrical Wiring Overview",
        "caption": (
            "Simplified cabinet wiring overview. Wire colors follow the cabinet convention: yellow "
            "data/signal, red 24 VDC, blue COM, green earth, black for 120 VAC or 5 VDC, "
            "and gray for the VFD three-phase feed and motor output."
        ),
        "size": [2200, 1260],
        "pdf_width_mm": 150,
        "pdf_viewbox": [35, 130, 2125, 1120],
        "show_title": False,
        "show_wire_labels": False,
        "drawio": True,
        "elements": [
            {"type": "box", "group": "overview_supervisor", "x": 60, "y": 155, "w": 270, "h": 125,
             "label": "Lab computer",
             "body": "Runs UI and data logging\nUSB link to Arduino", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_power", "x": 60, "y": 310, "w": 270, "h": 125,
             "label": "120 VAC input",
             "body": "Lab AC service\nSupply and heaters", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_power", "x": 60, "y": 665, "w": 270, "h": 125,
             "label": "240 VAC input",
             "body": "3-phase pump service\nFeeds pump drive", "label_size": 28, "body_size": 20},

            {"type": "box", "group": "overview_power", "x": 60, "y": 480, "w": 270, "h": 145,
             "label": "DC power supply",
             "body": "120 VAC to DC rails\n24 VDC, 5 VDC, COM", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_controller", "x": 400, "y": 155, "w": 270, "h": 980,
             "label": "Arduino Mega",
             "body": "Controller and I/O hub\nTelemetry + commands", "label_size": 28, "body_size": 20},
            {"type": "arrow", "group": "wire_24v", "points": [[400, 330], [670, 330]],
             "width": 3.0, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_com", "points": [[400, 370], [670, 370]],
             "width": 2.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_24v", "points": [[400, 455], [670, 455]],
             "width": 3.0, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_com", "points": [[400, 515], [670, 515]],
             "width": 2.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_earth", "points": [[400, 535], [670, 535]],
             "width": 2.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_240", "points": [[400, 728], [670, 728]],
             "width": 3.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_24v", "points": [[400, 765], [670, 765]],
             "width": 3.0, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_com", "points": [[400, 805], [670, 805]],
             "width": 2.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_black", "points": [[400, 910], [670, 910]],
             "width": 3.0, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_24v", "points": [[400, 1055], [670, 1055]],
             "width": 3.0, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_com", "points": [[400, 1095], [670, 1095]],
             "width": 2.6, "dashed": True, "head_size": 0},
            {"type": "arrow", "group": "wire_earth", "points": [[400, 1115], [670, 1115]],
             "width": 2.6, "dashed": True, "head_size": 0},

            {"type": "box", "group": "overview_instrumentation", "x": 740, "y": 153, "w": 300, "h": 160,
             "label": "TC backplate",
             "body": "Routes TC amplifier signals\nDistributes 5 VDC and COM", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_interface", "x": 740, "y": 443, "w": 300, "h": 125,
             "label": "Flow serial",
             "body": "RS-485 to Arduino UART\n24 VDC and COM to meter", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_interface", "x": 740, "y": 593, "w": 300, "h": 125,
             "label": "VFD serial",
             "body": "RS-485 to Arduino UART\nRJ-45 feedback path", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_interface", "x": 740, "y": 738, "w": 300, "h": 125,
             "label": "Speed converter",
             "body": "PWM to 0-10 V command\nPump speed reference", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_actuation", "x": 740, "y": 883, "w": 300, "h": 125,
             "label": "Heater relays",
             "body": "Arduino outputs switch AC\nPower to heater circuits", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_actuation", "x": 740, "y": 1028, "w": 300, "h": 125,
             "label": "LN valve relay",
             "body": "Arduino output switches DC\nPower to LN valve", "label_size": 28, "body_size": 20},

            {"type": "box", "group": "overview_instrumentation", "x": 1110, "y": 153, "w": 300, "h": 160,
             "label": "TC amplifier boards",
             "body": "MAX31856 TC front end\nDigital temperature data", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_interface", "x": 1110, "y": 593, "w": 300, "h": 125,
             "label": "VFD serial terminal",
             "body": "RJ-45 breakout terminal\nFeedback wiring", "label_size": 28, "body_size": 20},

            {"type": "box", "group": "overview_actuation", "x": 1470, "y": 590, "w": 280, "h": 250,
             "label": "VFD",
             "body": "AC in; motor out\nFeedback + speed ref.", "label_size": 28, "body_size": 20},

            {"type": "box", "group": "overview_instrumentation", "x": 1810, "y": 160, "w": 330, "h": 100,
             "label": "Thermocouples",
             "body": "System's temperature probes", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_instrumentation", "x": 1810, "y": 288, "w": 330, "h": 125,
             "label": "Pressure sensors",
             "body": "PMI, PMO, PTA transmitters\n0-5 VDC outputs to Arduino", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_instrumentation", "x": 1810, "y": 430, "w": 330, "h": 130,
             "label": "Flow meter",
             "body": "Flow and density reference\nRS-485 measurement data", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_actuation", "x": 1810, "y": 668, "w": 330, "h": 125,
             "label": "Pump motor",
             "body": "Circulation pump drive\nPowered by VFD output", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_actuation", "x": 1810, "y": 878, "w": 330, "h": 125,
             "label": "Heaters",
             "body": "Auxiliary heater circuits\nSwitched by relay outputs", "label_size": 28, "body_size": 20},
            {"type": "box", "group": "overview_actuation", "x": 1810, "y": 1028, "w": 330, "h": 125,
             "label": "LN valve",
             "body": "Controls LN coolant supply\nRelay-switched actuator", "label_size": 28, "body_size": 20},

            {"type": "wire", "group": "wire_data", "points": [[330, 190], [400, 190]], "label": "USB data", "label_dy": -34, "label_box_w": 55},
            {"type": "wire", "group": "wire_black", "points": [[330, 205], [400, 205]], "label": "USB 5 VDC", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[330, 220], [400, 220]], "label": "USB COM", "width": 2.6},
            {"type": "wire", "group": "wire_black", "points": [[230, 435], [230, 480]], "label": "120 VAC input", "width": 3.0},
            {"type": "wire", "group": "wire_earth", "points": [[180, 435], [180, 480]], "label": "earth input", "width": 2.6},

            {"type": "wire", "group": "wire_24v", "points": [[360, 330], [360, 1055]], "label": "24 VDC bus", "width": 3.0},
            {"type": "wire", "group": "wire_com", "points": [[375, 370], [375, 1095]], "label": "COM bus", "width": 2.6},
            {"type": "wire", "group": "wire_earth", "points": [[390, 535], [390, 1115]], "label": "earth bus", "width": 2.6},
            {"type": "wire", "group": "wire_24v", "points": [[330, 555], [360, 555]], "label": "24 VDC supply output", "width": 3.0},
            {"type": "wire", "group": "wire_com", "points": [[330, 575], [375, 575]], "label": "COM supply output", "width": 2.6},
            {"type": "wire", "group": "wire_earth", "points": [[330, 595], [390, 595]], "label": "earth supply output", "width": 2.6},
            {"type": "wire", "group": "wire_24v", "points": [[360, 330], [1810, 330]], "label": "24 VDC pressure", "width": 3.0},
            {"type": "wire", "group": "wire_com", "points": [[375, 370], [1810, 370]], "label": "COM pressure", "width": 2.6},
            {"type": "wire", "group": "wire_24v", "points": [[360, 455], [1810, 455]], "label": "24 VDC flow", "width": 3.0},
            {"type": "wire", "group": "wire_earth", "points": [[390, 535], [1810, 535]], "label": "flow ground", "width": 2.6},

            {"type": "wire", "group": "wire_black", "points": [[330, 380], [345, 380], [345, 910], [740, 910]], "label": "120 VAC heater feed", "width": 3.0},
            {"type": "wire", "group": "wire_black", "points": [[1040, 930], [1810, 930]], "label": "switched 120 VAC", "width": 3.0},
            {"type": "wire", "group": "wire_24v", "points": [[360, 1055], [740, 1055]], "label": "24 VDC relay feed", "width": 3.0},
            {"type": "wire", "group": "wire_com", "points": [[375, 1095], [740, 1095]], "label": "COM relay feed", "width": 2.6},
            {"type": "wire", "group": "wire_24v", "points": [[1040, 1055], [1810, 1055]], "label": "switched 24 VDC", "width": 3.0},
            {"type": "wire", "group": "wire_com", "points": [[375, 1095], [1810, 1095]], "label": "COM to valve", "width": 2.6},
            {"type": "wire", "group": "wire_earth", "points": [[390, 1115], [1810, 1115]], "label": "earth to valve", "width": 2.6},

            {"type": "wire", "group": "wire_240", "points": [[330, 728], [1470, 728]], "label": "3-phase 240 VAC", "width": 3.6},
            {"type": "wire", "group": "wire_data", "points": [[1750, 698], [1810, 698]], "label": "pump data", "width": 2.6},
            {"type": "wire", "group": "wire_240", "points": [[1750, 713], [1810, 713]], "label": "3-phase motor", "width": 3.6},

            {"type": "wire", "group": "wire_data", "points": [[670, 185], [740, 185]], "label": "TC data", "width": 2.6},
            {"type": "wire", "group": "wire_black", "points": [[670, 205], [740, 205]], "label": "5 VDC to TC backplate", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[670, 225], [740, 225]], "label": "COM to TC backplate", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1040, 185], [1110, 185]], "label": "TC data to amps", "width": 2.6},
            {"type": "wire", "group": "wire_black", "points": [[1040, 205], [1110, 205]], "label": "5 VDC to amps", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[1040, 225], [1110, 225]], "label": "COM to amps", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1410, 205], [1810, 205]], "label": "TC leads", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[670, 350], [1810, 350]], "label": "pressure signals", "width": 2.6},
            {"type": "wire", "group": "wire_black", "points": [[670, 475], [740, 475]], "label": "5 VDC to flow converter", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1810, 495], [1040, 495]], "label": "flow RS-485", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[740, 495], [670, 495]], "label": "flow UART", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[670, 515], [740, 515]], "label": "COM to flow converter", "width": 2.6},
            {"type": "wire", "group": "wire_black", "points": [[670, 620], [740, 620]], "label": "5 VDC to VFD converter", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[670, 640], [740, 640]], "label": "VFD UART", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[670, 660], [740, 660]], "label": "COM to VFD converter", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1040, 640], [1110, 640]], "label": "RS-485", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1410, 640], [1470, 640]], "label": "VFD RJ-45", "width": 2.6},
            {"type": "wire", "group": "wire_24v", "points": [[360, 765], [740, 765]], "label": "24 VDC to PWM converter", "width": 3.0},
            {"type": "wire", "group": "wire_data", "points": [[670, 785], [740, 785]], "label": "PWM", "width": 2.6},
            {"type": "wire", "group": "wire_com", "points": [[375, 805], [740, 805]], "label": "COM to PWM converter", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[1040, 785], [1470, 785]], "label": "0-10 V speed", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[670, 930], [740, 930]], "label": "heater relay control", "width": 2.6},
            {"type": "wire", "group": "wire_data", "points": [[670, 1075], [740, 1075]], "label": "LN relay control", "width": 2.6},

            {"type": "legend", "x": 60, "y": 1200,
             "items": ["wire_data", "wire_24v", "wire_black", "wire_com", "wire_earth", "wire_240"],
             "font_size": 34, "swatch_h": 22, "item_w": 350, "item_align": "center",
             "sample_style": "line", "sample_width": 52, "sample_thickness": 6,
             "text_gap": 12, "swatch_dy": 4},
        ],
    },
    {
        "slug": "05_tc_backplate_detail",
        "title": "Thermocouple Backplate Detail",
        "caption": (
            "Thermocouple backplate logic diagram shown in the installed orientation. The board is "
            "mounted upside down in the electrical box, so U9 is the top-left socket and U0 is the "
            "bottom-right socket. The connector feeds shared V_{in}, SDI/SDO, and SCK "
            "signals to the MAX31856 amplifier groups; GND is provided through the PCB area, and only "
            "the CS paths are separated by channel."
        ),
        "size": [1700, 980],
        "pdf_width_mm": 120,
        "pdf_viewbox": [35, 85, 1235, 760],
        "show_title": False,
        "show_wire_labels": False,
        "elements": [
            {"type": "panel", "x": 295, "y": 100, "w": 950, "h": 670,
             "fill": "#eefaf0", "stroke": "#238444", "stroke_width": 2.4, "radius": 8},

            {"type": "box", "group": "overview_controller", "x": 70, "y": 330, "w": 210, "h": 210,
             "label": "Arduino Mega",
             "body": "Digital bus master\nPower + select outputs", "label_size": 27, "body_size": 19,
             "fill": "#f6f3ff", "stroke": "#7450b8", "text": "#2f1f4c"},
            {"type": "box", "group": "tc_header", "x": 315, "y": 330, "w": 185, "h": 210,
             "label": "Connector",
             "body": "V_{in}, GND\nSDI/SDO, SCK\nCS0-CS9", "label_size": 26, "body_size": 19},
            {"type": "box", "group": "logic", "x": 555, "y": 160, "w": 260, "h": 125,
             "label": "Top CS",
             "body": "Channel select\nCS9-CS5 → U9-U5", "label_size": 27, "body_size": 18},
            {"type": "box", "group": "tc_header", "x": 555, "y": 330, "w": 260, "h": 210,
             "label": "Shared bus",
             "body": "V_{in}: power\nSDI: commands/settings\nSDO: temperature/status\nSCK: clock", "label_size": 27, "body_size": 18},
            {"type": "box", "group": "logic", "x": 555, "y": 585, "w": 260, "h": 125,
             "label": "Bottom CS",
             "body": "Channel select\nCS4-CS0 → U4-U0", "label_size": 27, "body_size": 18},

            {"type": "box", "group": "tc_header", "x": 930, "y": 160, "w": 300, "h": 125,
             "label": "Top Amplifiers",
             "body": "U6/TTO (T), U7/TMI (T)\nU8/THI (K), U9/THM (K)\nU5 spare", "label_size": 24, "body_size": 18,
             "dashed_border": True},
            {"type": "box", "group": "tc_header", "x": 930, "y": 585, "w": 300, "h": 125,
             "label": "Bottom Amplifiers",
             "body": "U3/TFO (T), U4/TTI (T)\nU0 spare, U1 spare\nU2 spare", "label_size": 24, "body_size": 18,
             "dashed_border": True},
            {"type": "note", "x": 315, "y": 625, "w": 185, "h": 105,
             "label": "Board ground",
             "body": "PCB area\nuses GND", "label_size": 23, "body_size": 17,
             "dashed_border": True},
            {"type": "wire", "group": "wire_vin", "points": [[280, 355], [315, 355]], "width": 2.6},
            {"type": "wire", "group": "wire_gnd", "points": [[280, 395], [315, 395]], "width": 2.6},
            {"type": "wire", "group": "wire_sdi_sdo", "points": [[280, 435], [315, 435]], "width": 2.6},
            {"type": "wire", "group": "wire_sck", "points": [[280, 475], [315, 475]], "width": 2.6},
            {"type": "wire", "group": "wire_cs", "points": [[280, 515], [315, 515]], "width": 2.6},

            {"type": "wire", "group": "wire_vin", "points": [[500, 355], [555, 355]], "width": 2.6},
            {"type": "wire", "group": "wire_sdi_sdo", "points": [[500, 435], [555, 435]], "width": 2.6},
            {"type": "wire", "group": "wire_sck", "points": [[500, 475], [555, 475]], "width": 2.6},
            {"type": "wire", "group": "wire_cs", "points": [[500, 515], [530, 515], [530, 222.5], [555, 222.5]], "width": 2.6},
            {"type": "wire", "group": "wire_cs", "points": [[530, 515], [530, 647.5], [555, 647.5]], "width": 2.6},

            {"type": "wire", "group": "wire_vin", "points": [[815, 355], [850, 355], [850, 212.5], [930, 212.5]], "width": 2.6},
            {"type": "wire", "group": "wire_sdi_sdo", "points": [[815, 435], [864, 435], [864, 232.5], [930, 232.5]], "width": 2.6},
            {"type": "wire", "group": "wire_sck", "points": [[815, 475], [878, 475], [878, 252.5], [930, 252.5]], "width": 2.6},
            {"type": "wire", "group": "wire_vin", "points": [[815, 355], [850, 355], [850, 617.5], [930, 617.5]], "width": 2.6},
            {"type": "wire", "group": "wire_sdi_sdo", "points": [[815, 435], [864, 435], [864, 637.5], [930, 637.5]], "width": 2.6},
            {"type": "wire", "group": "wire_sck", "points": [[815, 475], [878, 475], [878, 657.5], [930, 657.5]], "width": 2.6},
            {"type": "wire", "group": "wire_cs", "points": [[815, 222.5], [840, 222.5], [840, 192.5], [930, 192.5]], "width": 2.6},
            {"type": "wire", "group": "wire_cs", "points": [[815, 647.5], [840, 647.5], [840, 677.5], [930, 677.5]], "width": 2.6},
            {"type": "wire", "group": "wire_gnd", "points": [[407.5, 540], [407.5, 625]], "width": 2.5},

            {"type": "legend", "x": 295, "y": 800,
             "items": ["wire_vin", "wire_gnd", "wire_sdi_sdo", "wire_sck", "wire_cs"],
             "font_size": 23, "swatch_h": 18, "item_w": 190, "item_align": "center",
             "sample_style": "line", "sample_width": 48, "sample_thickness": 5,
             "text_gap": 12, "swatch_dy": 4},
        ],
    },
]
